/// <reference types="vite/client" />

// Build-time constants injected by `define` in vite.config.ts.
declare const __HYDRATE__: boolean
declare const __SITE_URL__: string
declare const __BUILD_YEAR__: number
declare const __COMMIT_HASH__: string
declare const __COMMIT_HASH_FULL__: string
declare const __COMMIT_SUBJECT__: string
declare const __COMMIT_BODY__: string
declare const __GITHUB_REPO__: string
declare const __PKG_VERSION__: string
declare const __BUILD_TIME__: string
declare const __BUILD_TIMESTAMP__: string
declare const __BUILD_PLATFORM__: string
declare const __BUILD_ARCH__: string
declare const __BUILD_NODE_VERSION__: string

// Virtual modules generated by scripts/blog-plugin.ts.
declare module 'virtual:blog-posts' {
  const posts: import('@/types/blog').BlogPost[]
  export default posts
}

declare module 'virtual:blog-content' {
  const rendered: import('@/types/blog').RenderedPostMap
  export default rendered
}
